name: template-hono-prisma-kysely

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:3000'
    environment:
      - STAGE=${STAGE}
      - DB_URL=${DB_URL}
      - TEST_DB_URL=${TEST_DB_URL}
